[versions]
android_plugin = "7.4.2"
kotlin = "1.8.21"


[libraries]
gradleplugins-android = { module = "com.android.tools.build:gradle", version.ref = "android_plugin" }
gradleplugins-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
